### ISSUE TITLE
For other editor

### ISSUE THREAD

**Issue by Alexey-T** [FlavourSys/Perv-ColorScheme#11]
Hi. Is it possible to make theme for Cudatext too [uvviewsoft.com] ?

**Comment by bigzed** [comment]
Feel free to adapt Perv to your edit, but please share it afterwards.

**Comment by Alexey-T** [comment]
I thought someone will do it:)

**Comment by micck** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [For other editor](https://trello.com/c/fo6CTqND/12-for-other-editor)

**Comment by Alexey-T** [comment]
I see- Card not found.
This card may be on a private board.

**Comment by micck** [comment]
Yes, sorry. Was trying out the Trello integration.
